# Generated by Django 5.1.4 on 2025-01-05 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Loptop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('price', models.PositiveBigIntegerField()),
                ('brand', models.CharField(max_length=255)),
                ('model', models.CharField(max_length=255)),
                ('category', models.CharField(max_length=255)),
                ('specs', models.TextField()),
                ('image_url', models.URLField()),
                ('source_url', models.URLField()),
                ('created_at', models.DateTimeField(blank=True, default='2000-01-01', null=True)),
                ('extra_data', models.JSONField(blank=True, default=dict, null=True)),
                ('scrawled_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
