# Generated by Django 5.1.4 on 2025-01-07 10:55

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Laptop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('price', models.PositiveBigIntegerField(default=0)),
                ('comments', models.JSONField(blank=True, default=dict, null=True)),
                ('brand', models.CharField(max_length=255)),
                ('model', models.CharField(max_length=255)),
                ('category', models.CharField(max_length=255)),
                ('specs', models.TextField()),
                ('image_urls', models.JSONField(blank=True, default=dict)),
                ('source_url', models.URLField()),
                ('created_at', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('extra_data', models.JSONField(blank=True, default=dict, null=True)),
                ('crawled_at', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Phones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('price', models.PositiveBigIntegerField(default=0)),
                ('brand', models.CharField(max_length=255)),
                ('model', models.CharField(max_length=255)),
                ('category', models.CharField(max_length=255)),
                ('specs', models.JSONField(default=dict)),
                ('extra_data', models.JSONField(default=dict)),
                ('source_url', models.URLField()),
                ('crawled_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('image_urls', models.JSONField(blank=True, default=dict, null=True)),
            ],
        ),
    ]
