# Generated by Django 5.1.4 on 2025-01-05 07:45

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_loptop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loptop',
            name='created_at',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
