# Generated by Django 5.1.4 on 2025-01-01 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_loptop', '0002_loptop_extra_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='loptop',
            name='year',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
