# Generated by Django 5.1.4 on 2025-01-05 07:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_loptop', '0002_alter_loptop_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='LaptopPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.PositiveBigIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('laptop', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='price_history', to='django_loptop.loptop')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
