# Generated by Django 5.1.4 on 2025-01-05 08:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_loptop', '0003_laptopprice'),
    ]

    operations = [
        migrations.RenameField(
            model_name='loptop',
            old_name='scrawled_at',
            new_name='crawled_at',
        ),
    ]
