# Generated by Django 5.1.4 on 2025-01-01 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_loptop', '0004_alter_loptop_extra_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loptop',
            name='year',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
