# Generated by Django 5.1.4 on 2025-01-05 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_loptop', '0004_rename_scrawled_at_loptop_crawled_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loptop',
            name='crawled_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
