# Generated by Django 5.1.4 on 2025-01-04 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_loptop', '0005_alter_loptop_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loptop',
            name='source_url',
            field=models.URLField(unique=True),
        ),
    ]
