# Generated by Django 5.1.4 on 2025-01-05 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_loptop', '0006_remove_loptop_image_url_loptop_image_urls'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loptop',
            name='image_urls',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
