# Generated by Django 5.1.4 on 2025-01-04 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_loptop', '0006_alter_loptop_source_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='LaptopPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RenameField(
            model_name='loptop',
            old_name='year',
            new_name='created_at',
        ),
        migrations.AddField(
            model_name='loptop',
            name='category',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='loptop',
            name='scrawled_at',
            field=models.DateTimeField(auto_now_add=True, default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='loptop',
            name='source_url',
            field=models.URLField(),
        ),
    ]
