# Generated by Django 5.1.4 on 2025-01-04 09:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_loptop', '0007_laptopprice_rename_year_loptop_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='laptopprice',
            name='laptop',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='django_loptop.loptop'),
            preserve_default=False,
        ),
    ]
