# Generated by Django 5.1.4 on 2025-01-05 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_loptop', '0007_alter_loptop_image_urls'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LaptopPrice',
        ),
    ]
