# Generated by Django 5.1.4 on 2025-01-04 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_loptop', '0008_laptopprice_laptop'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='laptopprice',
            name='laptop',
        ),
    ]
