# Generated by Django 5.1.4 on 2025-01-05 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_loptop', '0009_alter_loptop_price'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Loptop',
            new_name='Laptop',
        ),
    ]
