# Generated by Django 5.1.4 on 2025-01-04 10:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_loptop', '0009_remove_laptopprice_laptop'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='laptopprice',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='laptopprice',
            name='laptop',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='price_history', to='django_loptop.loptop'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='laptopprice',
            name='price',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='loptop',
            name='created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
