# Generated by Django 5.1.4 on 2025-01-04 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_loptop', '0010_alter_laptopprice_options_laptopprice_laptop_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laptopprice',
            name='price',
            field=models.PositiveBigIntegerField(),
        ),
    ]
