# Generated by Django 5.1.4 on 2025-01-07 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_loptop', '0012_laptop_product_id_phones_product_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='laptop',
            name='comments',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
