# Generated by Django 5.1.4 on 2024-12-31 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('year', models.IntegerField()),
                ('image_url', models.URLField(blank=True, max_length=500)),
                ('source_url', models.URLField(max_length=500)),
                ('extra_data', models.JSONField(blank=True, null=True)),
            ],
        ),
    ]
